'use strict';
const $=id=>document.getElementById(id);
const labels={on:'일본어 음독',korean:'한국어 음훈',kun:'일본어 훈독'};
let groups=new Set(['a']),type='on',session=null;
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function buildPool(selected,kind){return window.KANJI_DATA.filter(r=>selected.has(r.group)).flatMap(r=>kind==='kun'?r.kun.map((k,i)=>({id:r.id+'-'+i,record:r,word:k.word,answer:k.reading,meaning:k.meaning})):kind==='on'?(r.on.length?[{id:r.id,record:r,word:r.kanji,answer:r.on.join('・'),meaning:''}]:[]):[{id:r.id,record:r,word:r.kanji,answer:r.korean,meaning:''}]);}
function choiceAnswers(q,pool,kind){
 const unique=[...new Set(pool.map(x=>x.answer))].filter(a=>a!==q.answer);
 const suffix=kind==='kun'?q.word.slice(q.record.kanji.length):'';
 if(!suffix)return shuffle([q.answer,...shuffle(unique).slice(0,3)]);
 // Prefer the same written okurigana, then readings with the same ending.
 const exact=new Set(pool.filter(x=>x.word.slice(x.record.kanji.length)===suffix).map(x=>x.answer));
 const preferred=shuffle(unique.filter(a=>exact.has(a)));
 const sameEnding=shuffle(unique.filter(a=>!exact.has(a)&&a.endsWith(suffix)));
 const fallback=shuffle(unique.filter(a=>!exact.has(a)&&!a.endsWith(suffix)));
 return shuffle([q.answer,...[...preferred,...sameEnding,...fallback].slice(0,3)]);
}
function updatePool(){const n=buildPool(groups,type).length;$('pool-note').textContent=`선택한 범위에서 ${n}문제 출제 가능`;$('start').disabled=!n;}
document.querySelectorAll('.row').forEach(b=>b.addEventListener('click',()=>{const g=b.dataset.group;if(groups.has(g)){if(groups.size===1)return;groups.delete(g);}else groups.add(g);b.classList.toggle('active',groups.has(g));b.setAttribute('aria-pressed',groups.has(g));updatePool();}));
document.querySelectorAll('.type').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.type;document.querySelectorAll('.type').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});updatePool();}));
function show(view){['welcome','quiz','results'].forEach(id=>$(id).hidden=id!==view);}
function start(questions,pool,kind,mode){session={questions,pool,kind,mode,index:0,correct:0,missed:[],answered:false};show('quiz');$('quiz-label').textContent=labels[kind]+' 연습';renderQuestion();if(innerWidth<781)$('quiz').scrollIntoView({behavior:'smooth',block:'start'});}
$('start').addEventListener('click',()=>{const pool=buildPool(groups,type),n=$('limit').value==='all'?pool.length:Math.min(Number($('limit').value),pool.length);start(shuffle(pool).slice(0,n),pool,type,$('mode').value);});
function renderQuestion(){const s=session,q=s.questions[s.index];s.answered=false;$('position').textContent=`${s.index+1} / ${s.questions.length} 문제`;$('score').textContent=`정답 ${s.correct}개`;$('progress-bar').style.width=(s.index/s.questions.length*100)+'%';$('prompt').textContent=s.kind==='on'?'이 한자의 음독을 모두 골라주세요.':s.kind==='kun'?'이 형태의 훈독은 무엇일까요?':'이 한자의 한국어 뜻과 음은 무엇일까요?';if(s.mode==='write'&&s.kind==='on')$('prompt').textContent='이 한자의 음독을 모두 입력하세요.';$('word').textContent=q.word;$('word').classList.toggle('long',q.word.length>2);$('hint').textContent=s.kind==='kun'?q.meaning:'';$('answer-help').textContent=s.mode==='write'?(s.kind==='on'?'히라가나·가타카나 모두 가능 · 여러 음은 쉼표 또는 공백으로 구분':s.kind==='korean'?'뜻과 음을 함께 입력하세요. 예: 넓을 광':'단어 전체의 읽기를 입력하세요. 예: ひろめる'):'보기를 선택하면 정답을 확인합니다.';$('feedback').hidden=true;$('next').hidden=true;$('choices').replaceChildren();$('choices').hidden=s.mode!=='choice';$('write-area').hidden=s.mode!=='write';$('answer').value='';$('answer').disabled=false;$('check').disabled=false;
 if(s.mode==='choice'){choiceAnswers(q,s.pool,s.kind).forEach(a=>{const b=document.createElement('button');b.type='button';b.className='choice';b.textContent=a;b.addEventListener('click',()=>grade(a,b));$('choices').append(b);});}else $('answer').focus();
}
function normalize(a){return a.normalize('NFKC').trim().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));}
function isCorrect(value,q,kind){if(kind==='on'){const split=a=>[...new Set(normalize(a).split(/[\s,、・/]+/).filter(Boolean))].sort().join('|');return split(value)===split(q.answer);}if(kind==='korean')return normalize(value).replace(/\s/g,'')===normalize(q.answer).replace(/\s/g,'');return normalize(value)===normalize(q.answer);}
function line(parent,text,cls){const el=document.createElement('div');el.textContent=text;if(cls)el.className=cls;parent.append(el);}
function grade(value,button){const s=session;if(!s||s.answered)return;const q=s.questions[s.index];s.answered=true;const ok=isCorrect(value,q,s.kind);if(ok)s.correct++;else s.missed.push({...q,user:value});document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add('correct');});if(button&&!ok)button.classList.add('wrong');$('answer').disabled=true;$('check').disabled=true;const f=$('feedback');f.replaceChildren();f.classList.toggle('wrong',!ok);const b=document.createElement('b');b.textContent=ok?'정답입니다!':'다시 기억해 보세요.';f.append(b);line(f,q.answer,'answer-value');if(!ok&&value)line(f,'내 답: '+value);line(f,q.record.kanji+(q.record.old?' ('+q.record.old+')':'')+' · '+q.record.korean);if(s.kind==='kun')line(f,q.word+' → '+q.answer+' · '+q.meaning);else if(q.record.kun.length)line(f,'훈독: '+q.record.kun.map(k=>k.word+' '+k.reading).join(' / '));if(s.kind!=='on'&&q.record.on.length)line(f,'음독: '+q.record.on.join('・'));f.hidden=false;$('score').textContent=`정답 ${s.correct}개`;$('next').textContent=s.index===s.questions.length-1?'결과 보기 →':'다음 문제 →';$('next').hidden=false;$('next').focus();}
$('answer-form').addEventListener('submit',e=>{e.preventDefault();const value=$('answer').value.trim();if(value)grade(value);});
$('next').addEventListener('click',()=>{if(!session?.answered)return;session.index++;if(session.index===session.questions.length)finish(false);else renderQuestion();});
$('end').addEventListener('click',()=>finish(true));
function finish(early){const s=session,done=s.index+(s.answered?1:0),total=early?done:s.questions.length;show('results');const r=$('results');r.replaceChildren();const eye=document.createElement('p');eye.className='eyebrow';eye.textContent=early?'연습 종료':'연습 완료';r.append(eye);const title=document.createElement('h2');title.textContent=total===0?'다음에 다시 시작해요.':s.correct===total?'모두 정확하게 읽었어요.':'한 글자 더 익숙해졌어요.';r.append(title);const number=document.createElement('div');number.className='result-number';number.textContent=s.correct+' ';const denominator=document.createElement('small');denominator.textContent='/ '+total;number.append(denominator);r.append(number);const p=document.createElement('p');p.textContent=total?`정답률 ${Math.round(s.correct/total*100)}% · ${labels[s.kind]}`:'아직 답한 문제가 없습니다.';r.append(p);const actions=document.createElement('div');actions.className='result-actions';const again=document.createElement('button');again.className='primary';again.textContent='같은 범위 다시 풀기';again.onclick=()=>start(shuffle(s.questions),s.pool,s.kind,s.mode);actions.append(again);if(s.missed.length){const retry=document.createElement('button');retry.className='secondary';retry.textContent=`틀린 ${s.missed.length}문제 다시 풀기`;retry.onclick=()=>start(shuffle(s.missed),s.pool,s.kind,s.mode);actions.append(retry);}const home=document.createElement('button');home.className='secondary';home.textContent='설정으로 돌아가기';home.onclick=()=>{show('welcome');$('start').focus();};actions.append(home);r.append(actions);if(s.missed.length){const h=document.createElement('h3');h.textContent='다시 볼 한자';r.append(h);s.missed.forEach(q=>{const row=document.createElement('div');row.className='review';const word=document.createElement('strong');word.textContent=q.word;const details=document.createElement('div');details.textContent=q.answer;const small=document.createElement('small');small.textContent=(q.meaning||q.record.korean)+' · 내 답: '+q.user;details.append(small);row.append(word,details);r.append(row);});}again.focus();}
updatePool();
